### ISSUE TITLE
How to listen to status: back, front

### ISSUE THREAD

**Issue by karljoaquin** [BrunoJurkovic/flip_card#11]
I'm a newbie, so i'm not sure if my question is reasonable.

Is it possible to listen to the card status to find out which side of the card is active?

I have a random deck of cards. If i pick a random card with a button, i would like to  always show the front side first.

**Comment by feibyte** [comment]
Thank you for your feedback. 
I'm not sure I got your point.  We do have a call back `onFlip`, is that what you want?
Or you wanna take the control of it?

**Comment by karljoaquin** [comment]
Hi, sorry if i was not clear.

What i meant: the card has a "front" and a "back." Is it possible the check the present status (is the card facing front or back)?.

I see now that there is a bool "isFront". I should probably work with that?

**Comment by feibyte** [comment]
@karljoaquin  Yep, You could use it.  
Also, it might in the progress of moving to front.

**Comment by karljoaquin** [comment]
Alright! Thanks for pointing that out. I'll try this ;)

**Comment by feibyte** [comment]
@karljoaquin  Can I  close this issue?
