### ISSUE TITLE
Generates Error in a List View

### ISSUE THREAD

**Issue by skaterdude** [BrunoJurkovic/flip_card#12]
This seems to generate an error when I place it in a Column.  When wrapped in an Expanded, the error goes away.  However, then when I try to put several in a ListView, this error pops up again:

"The following assertion was thrown during performResize():
"Vertical viewport was given unbounded height.
"Viewports expand in the scrolling direction to fill their container.In this case, a vertical
viewport was given an unlimited amount of vertical space in which to expand. This situation
typically happens when a scrollable widget is nested inside another scrollable widget."

I also tried wrapping it in a sized box, but that didn't help.  I'm new at this, so perhaps I'm not understanding the right way to constrain it?  Looking through the code, and the way it looks, it appears that the animation goes outside the bounds of the image (because of the 3D affect, I assume).  Is this part of the issue?

Here's part of the code.  I extracted the instance into a new widget so I could easily put a bunch of these in a ListView:  

Widget build(BuildContext context) {
    return SizedBox(height: 300,
      child: Expanded(
        child: FlipCard(
          direction: FlipDirection.HORIZONTAL,
          flipOnTouch: true,
          front: Container(
            padding: EdgeInsets.all(10),
            decoration: BoxDecoration(
                color: Colors.white,
                image: DecorationImage(image: AssetImage(frontURI))),
          ),
          back: Container(
            padding: EdgeInsets.all(10),
            decoration: BoxDecoration(
                color: Colors.blue,
                image: DecorationImage(image: AssetImage(rearURI))),
          ),
        ),
      ),
    );
  }

**Comment by feibyte** [comment]
@skaterdude  Thanks for your feedback.
I am not able to guess the reason.  
Could you simply replace the flip_card with AssetImage to see if it works well?
If do, could you pls post whole code?

**Comment by skaterdude** [comment]
I found the problem after a LOT of reading about rendering.  It's this statement:
      fit: StackFit.expand,
which tries to make it as big as possible.  When I change it to:
      fit: StackFit.passthrough,
the error goes away.  So I guess it depends upon the context where you're using it.

Hope that helps!

**Comment by feibyte** [comment]
@skaterdude  Thanks a lot.
Can I close it now?

**Comment by skaterdude** [comment]
Sure, if you've checked my proposed solution and updated / tested the code.  Or, alternatively, if you don't think the solution is generally applicable.
