### ISSUE TITLE
onFlipped listener?

### ISSUE THREAD

**Issue by txufiknr** [BrunoJurkovic/flip_card#14]
Any way or example to listen when my widget flip animation is done (when the back side is fully shown)?

**Comment by feibyte** [comment]
At the moment, there's just callback indicating the begin of animation. 
Is what you want is something like  `onFlipDone`  or onFlip(status)?

**Comment by txufiknr** [comment]
`onFlipDone` is fine along with existing `onFlip`, I need to do some stuff at the end of animation, thank you.
