### ISSUE TITLE
0.4.3 no longer flips widgets properly because of the transform change ...

### ISSUE THREAD

**Issue by ssbaval** [BrunoJurkovic/flip_card#18]
Upgraded from 0.4.0 to 0.4.3 - now when we flip the cards, the animation and overall affect is nothing like what it used to be and what is shown in the animated gif. It is like left and right sides shrink to the middle which doesnt give the impression that the cards are **FLIPPED**

Version 0.4.0, 0.4.1, 0.4.2 all work perfectly and animation is great. **0.4.3** where transform is changed is where the issue lies. Can we have this parameterized where we can change this ourselves if need be.

**Comment by feibyte** [comment]
@ssbaval  Thanks for your feedback. 
Could you please add more information on this issue? Like the OS system.
As I just tested on my simulation.

**Comment by hiepvn** [comment]
@fedeoo 

Same here. Flip effect not work perfectly. Please check gif image below.
I used code from your example.

![ezgif-4-9780c4f46879](https://user-images.githubusercontent.com/2033402/67476050-3c5e9380-f692-11e9-921c-0d80e11f4730.gif)


```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)
```

**Comment by sallymariehollywood** [comment]
Same here . Have gone back to old version 0.4.2 which works as intended.

**Comment by feibyte** [comment]
Thanks for the feedback and sorry for the inconvenience.
I'm going to revert the change. Just FYI, @alongruss Thanks anyway.

**Comment by feibyte** [comment]
0.4.4 was released.
