### ISSUE TITLE
FlipCard does not work when animation incorporated in my code to create Grid

### ISSUE THREAD

**Issue by Rahul221991** [BrunoJurkovic/flip_card#2]
I want to create grid of flipcards and want to have count each time user flips the card. So I used following code. I maintained animation for each card.

class _GridFlipCardState extends State<GridFlipCard>
    with TickerProviderStateMixin {
  List<AnimationController> _controllers = List<AnimationController>();
  List<Animation<double>> _frontRotations = List<Animation<double>>();
  List<Animation<double>> _backRotations = List<Animation<double>>();
  List<bool> isFronts = List<bool>();
  int cardsCount = 4;
  int backCount = 0;
  final FlipDirection _flipDirection = FlipDirection.HORIZONTAL;

  @override
  void initState() {
    super.initState();
    for (int i = 0; i < cardsCount; i++) {
      final controller = AnimationController(
          duration: Duration(milliseconds: 500), vsync: this);
      _controllers.add(controller);

      final _frontRotation = TweenSequence(
        <TweenSequenceItem<double>>[
          TweenSequenceItem<double>(
            tween: Tween(begin: 0.0, end: pi / 2)
                .chain(CurveTween(curve: Curves.linear)),
            weight: 50.0,
          ),
          TweenSequenceItem<double>(
            tween: ConstantTween<double>(pi / 2),
            weight: 50.0,
          ),
        ],
      ).animate(_controllers.elementAt(i));
      _frontRotations.add(_frontRotation);

      final _backRotation = TweenSequence(
        <TweenSequenceItem<double>>[
          TweenSequenceItem<double>(
            tween: Tween(begin: 0.0, end: pi / 2)
                .chain(CurveTween(curve: Curves.linear)),
            weight: 50.0,
          ),
          TweenSequenceItem<double>(
            tween: ConstantTween<double>(pi / 2),
            weight: 50.0,
          ),
        ],
      ).animate(_controllers.elementAt(i));
      _backRotations.add(_backRotation);

      isFronts.add(true);
    }
  }

  void toggleCard(int index) {
    if (isFronts[index]) {
      _controllers[index].forward();
    } else {
      _controllers[index].reverse();
    }
    isFronts[index] = !isFronts[index];
    setState(() {
      backCount++;
    });
  }

@override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(top: 100),
      child: Column(
        children: <Widget>[
          Expanded(
            flex: 1,
            child: GridView.count(
              crossAxisCount: 4,
              children: List.generate(cardsCount, (index) {
                return GestureDetector(
                  onTap: () => toggleCard(index),
                  child: Stack(
                    fit: StackFit.expand,
                    children: <Widget>[
                      AnimationCard(
                        child: CircleAvatar(
                          backgroundColor: Colors.red,
                          radius: 50,
                        ),
                        animation: _frontRotations[index],
                        direction: _flipDirection,
                      ),
                      AnimationCard(
                        child: CircleAvatar(
                          backgroundColor: Colors.red,
                          radius: 50,
                        ),
                        animation: _backRotations[index],
                        direction: _flipDirection,
                      ),
                    ],
                  ),
                );
              }),
            ),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    for (var i = 0; i < cardsCount; i++) {
      _controllers[i].dispose();
    }

    super.dispose();
  }
}

The AnimationCard card is same as yours. But the output I get is not same as the single FlipCard.

![image](https://user-images.githubusercontent.com/36102116/52033488-1e249680-254b-11e9-94f8-80f002b67eda.png)

When I click on some card, it turns to be disappear. 
![image](https://user-images.githubusercontent.com/36102116/52033529-49a78100-254b-11e9-898f-59aa620997c4.png)

Could you let me know, what am I missing.

Thanks...

**Comment by alongruss** [comment]
Why are you changing/using the code inside the flip_card widget?
you should probably just add the package in your pubspec.yaml, import it into your page widget and call it like so:
```
import 'package:flutter/material.dart';
import 'package:flip_card/flip_card.dart';

class GridPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: return GridView.builder(
        itemBuilder: (BuildContext context, int index) => FlipCard(
front: <your front widget>,
back: <your back widget>
),
        itemCount: <your item count>,
        gridDelegate:
          SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: <your cross axis count>),
      ),
    );
  }
}
```

**Comment by BrunoJurkovic** [comment]
This issue has been dormant for a while, please open a new issue if the error still exists.
