### ISSUE TITLE
[feature] Unlimited sides

### ISSUE THREAD

**Issue by leonardocustodio** [BrunoJurkovic/flip_card#22]
It is not an issue but it would be nice to allow to have cards with more than two sides.

I know it is not a "real world card". But it is pretty nice to use this kind of animation with multiple "screens" for example for form filling.

PS.: I'm already doing this by using state management and the key with toggleCard but we can't control the animation this way. So instead of going from right to left and then when toggling going from left to right. It would be nice if it was possible to go from right to left multiple times.

**Comment by feibyte** [comment]
Could you please put a gif here?  🤔 It sounds more like a card stacks.   https://tympanus.net/Development/CardStackEffects/
