### ISSUE TITLE
glitches with back container if apply Transform.rotate for FlipCard

### ISSUE THREAD

**Issue by Vasya-M** [BrunoJurkovic/flip_card#23]
I wanted to add swiping Flip card with applying translation and rotation, like in tinder/badoo, but when I added rotation animation I get glitches with `back` widget(`container `with setuped `color`).
Also reproducable with simple text.
Work for both as on emulator as real device.
I tried to add `image` for as `back` widget and did not get glitches.
![photo_2020-02-29_23-02-05](https://user-images.githubusercontent.com/33808928/75615029-a78c0b00-5b47-11ea-8ac5-c459160f7551.jpg)
code sample
```
 GestureDetector(
    onHorizontalDragEnd: (DragEndDetails details) {
        total_x_offset = 0;
        rotation_angle = 0; 
        _redraw();
        cardKey.currentState.toggleCard();
    },

    onHorizontalDragUpdate: (DragUpdateDetails details) {
        total_x_offset += details.primaryDelta;
        rotation_angle = total_x_offset / 400;
        _redraw();
    },

    child: Container(
        child: Transform.rotate(
            key: cardKey,
            angle: rotation_angle,
            child: FlipCard(  
                front: Container( width: 100, height: 100, color: Colors.blue),
                back:  Container( width: 100, height: 100, color: Colors.yellow),
            )
        )
    )
 )
```

**Comment by leonardocustodio** [comment]
Not sure if it is related but I also have a glitch:

![glitchback](https://user-images.githubusercontent.com/5619696/76147142-efdf8780-6077-11ea-8e1d-270ce9aa205b.jpg)

In the back of the card it appears a very thin line in the rotation axis. I not sure what is causing it.

**Comment by feibyte** [comment]
Thanks for reporting. @leonardocustodio  
It appears occasionally.  I still have no clue on that line. Basically, when rotation is close to 90 degrees, it looks a line.

**Comment by Vasya-M** [comment]
@fedeoo, I made my own flip card with using IndexedStack for showing only the needed side(widget), and all glitches described above are gone.
The root of glitches is in storing hidden(Back) widget in 90 degrees rotated state.
This approach looks like bad workaround or hack.
IMHO.
@leonardocustodio if you want I can share with a fixed version( but it remade for my needs, and devoid some interfaces)

**Comment by feibyte** [comment]
@Vasya-M  Would you like to contribute to this repo? Or Would you like to take over it as I am not working on flutter repo ATM?  I really appreciate your help.

**Comment by leonardocustodio** [comment]
@Vasya-M if you can please share with us or make a pull request. I would appreciate to have this glitch fixed.

**Comment by petro-i** [comment]
I also experience glitch. It looks absolutely terrible on iOS devices with Flutter 1.17+ (Metal Skia rendering) on real devices, on iOS simulator also slightly visible on Flutter 1.12 but not observed on real devices. No problem on Android. Glitch is better visible if you put FlipCard widget (light colors like yellow) on PageView and move pages.

**Comment by BrunoJurkovic** [comment]
Does this issue still persist?

**Comment by bhavykoshti** [comment]
@Vasya-M can you please share your code so that we can update as well?
