### ISSUE TITLE
Add constructor option to build the card with the back face

### ISSUE THREAD

**Issue by Delgan** [BrunoJurkovic/flip_card#24]
Hey!

Your library is very useful and the animation is really nice, thanks for sharing your work. :+1: 

I had one suggestion: would it be possible to add a new parameter to the `FlipCard()` widget to enable the card displaying the back face while first being built?
Sometimes, I need to re-create a whole page of my application using a past state, and being able to initialize the card based on its previous state would be pretty useful.

What do you think?

**Comment by feibyte** [comment]
Sorry, I am not sure I get your point. Do you mean?
You have built a FlipCard:
```
FlipCard(front: A, back: B)
```
And sometimes you wanna render 
```
FlipCard(front: B, back: A)
```
Or 
```
FlipCard(front: A, back: B, side: previous_state)
```

**Comment by Delgan** [comment]
@fedeoo I'm interested by:

```dart
FlipCard(front: A, back: B, side: previous_state)
```
I can already reverse the constructor using `FlipCard(front: B, back: A)` but this implies the animation will be executed in the wrong direction.

**Comment by BrunoJurkovic** [comment]
@Delgan Is there still a need for this feature or can I close this issue?

**Comment by Delgan** [comment]
Hi @BrunoJurkovic. I still believe that this would be quite a useful feature to add to this library. :+1: 

But it's not a big deal, I can live without it. ;)

**Comment by BrunoJurkovic** [comment]
> Hi @BrunoJurkovic. I still believe that this would be quite a useful feature to add to this library. :+1: 
> 
> 
> 
> But it's not a big deal, I can live without it. ;)

Thanks for letting me know, would you be interested in making a pull request with the said feature or do you want me to write it? Either way works for me :)

**Comment by Delgan** [comment]
@BrunoJurkovic Ok, I'll try to take a look at it and (hopefully) open a PR this week-end. :smile:

**Comment by BrunoJurkovic** [comment]
Perfect, thanks for your interest and I assure you it is much appreciated! Feel free to message here if you have any issues with implementing this :))

**Comment by BrunoJurkovic** [comment]
@Delgan Hey there, are you still planning to make this change or should I do it myself? Let me know :)

**Comment by mchilvers** [comment]
Hiya, Great package - thanks for the work on it! I would also like this feature, for the same reasons i.e. at build time I want the side that is initially showing to be determined by saved state.

**Comment by BrunoJurkovic** [comment]
Thanks for letting me know, expect a update soon @mchilvers :)

**Comment by mchilvers** [comment]
> Thanks for letting me know, expect a update soon @mchilvers :)

Brilliant - thanks!

**Comment by Delgan** [comment]
@BrunoJurkovic Sorry I hadn't the time to look at it. :grimacing: 

Please give me a second chance this weekend (unless you really want to implement it yourself). :grin:

**Comment by BrunoJurkovic** [comment]
Sure! Go ahead!
