### ISSUE TITLE
Can the back card be dynamically changed?

### ISSUE THREAD

**Issue by rdhillbb** [BrunoJurkovic/flip_card#25]
Is it possible to change the back card? 

A->B
A<-B
A->C (Is a diffrent widget)

**Comment by feibyte** [comment]
No supported.  It sounds a little bit strange. 
I think it could be done by rendering card.  You can listen to the change events and rerender the card.  Is it satisfied your requirements?

**Comment by rdhillbb** [comment]
Thank you for our response.
Basically, I want to simulate turning the page of a book.

I am going to ask a remedial question as I am new to dart/Flutter, how do I listen to change events ?

Thank you again for your response. 



Randolph Davis Hill
Fat Tree IO
ipnudavis@fattree.io
+855-969-007-829
+1209-232-1157
