### ISSUE TITLE
Vertical line apperes  in ios device but working perfectly on Android

### ISSUE THREAD

**Issue by 07onkar07** [BrunoJurkovic/flip_card#3]
![IMG_3251](https://user-images.githubusercontent.com/48351787/54282186-78405f00-45c1-11e9-8bce-c8247755aa76.PNG)

A vertical line appears in the ios device but working perfectly on Android.

**Comment by feibyte** [comment]
Sorry of replying late. Could you pls add more information on this issue?   Which version of flutter are you using?

**Comment by feibyte** [comment]
I've updated flutter to the latest version, but I still failed to reproduce your problem.
Flutter --version
```
Flutter 1.3.14-pre.63 • channel master • https://github.com/flutter/flutter.git
Framework • revision 94c68e1115 (2 hours ago) • 2019-03-23 03:53:41 -0400
Engine • revision 62c88d6902
Tools • Dart 2.2.1 (build 2.2.1-dev.2.0 None)
```
Could you pls add more details on it?

**Comment by yutae** [comment]
@fedeoo 

It is still issue on iOS device (not simulator)

```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (7 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

**Comment by feibyte** [comment]
What's the iOS version?

**Comment by alongruss** [comment]
Vertical lines also appear on horizontal flipping cards on Android 5.1 - As if the other side of the card is just squashed when flipped over (instead of also having 0 opacity). It looks like the visual artifact is more noticeable when: the inner widgets have high elevation, or, when they are rotated.

Might need to set values on a wrapping Visibility widget at the end of the flip animation.

![image](https://user-images.githubusercontent.com/23163146/64504079-a1268000-d2d6-11e9-90e2-03e4d2429d00.png)

**Comment by alongruss** [comment]
Upon further inspection it seems that the transform operation used for flipping the card is not taking previous transforms into account...

**Comment by alongruss** [comment]
@fedeoo - Fixed by changing `transform.setEntry(3, 2, 0.001);` to `transform.setEntry(3, 2, 0.000);` in the AnimationCard widget.

**Comment by feibyte** [comment]
@alongruss  Great! I was on vacation last week.  Do you favor raising a PR?

**Comment by hm122** [comment]
Is this fix working? I have clients which reported a similar issue, vertical lines in the center, but I was unable to reproduce the problem. 

Attached a screenshot from a client. In the red circle a part of a TextField from the back side is shining through.

<img width="139" alt="Screenshot 2020-04-11 at 11 41 30" src="https://user-images.githubusercontent.com/13405226/79040575-bc999680-7be9-11ea-8bc9-24fcb370188d.png">

**Comment by hm122** [comment]
Seems like the fix of @alongruss is working, thank you! Please @fedeoo, is it possible to deploy a new version with this fix?

**Comment by feibyte** [comment]
@hm122   I tried that and it brought another issue.

**Comment by hm122** [comment]
Thanks for your answer. What issue arised? Is there another solution?

Am 12. April 2020 10:46:55 MESZ schrieb "小乙哥" <notifications@github.com>:

**Comment by hm122** [comment]
Thanks for your answer @fedeoo . What issue did arise? Is there another solution?

**Comment by feibyte** [comment]
Here is the issue https://github.com/fedeoo/flip_card/issues/18

**Comment by feibyte** [comment]
@hm122  I've tried IndexStack instead of Stack and I found it somehow affected the layout.

**Comment by hm122** [comment]
@fedeoo ok, thank you. But did you try the change @alongruss mentioned? (Fixed by changing transform.setEntry(3, 2, 0.001); to transform.setEntry(3, 2, 0.000);). I've tried that and it seems to work correctly. Did you try that? What was the reason for setting the value to 0.001 instead of 0?

**Comment by feibyte** [comment]
It brought another issue  #18 
And then I changed back to `0.001`

**Comment by LugonjaAleksandar** [comment]
This issue still exists on version 0.4.4, it should not be closed bug report. It's caused by back Widget of the library, and once I apply Opacity workaround on it it disappears. Problem is Opacity has to apply on the widget inside the library based on current rotation angle, and not on back or front Widget.

**Comment by TheBestMoshe** [comment]
This issue still exists in 0.4.4


> Fixed by changing `transform.setEntry(3, 2, 0.001);` to `transform.setEntry(3, 2, 0.000);` in the AnimationCard widget.

@alongruss  Where do I make this change?

**Comment by sallypeters** [comment]
@TheBestMoshe The change recommended by @alongruss Completely changes the flip animation to a squash/expand animation which defeats the object of the plugin.  There have been a few fixes to this plugin which have negatively impacted the effectiveness of the flip animation, i.e 4.4, 4.3 (Transform entry) , and 4.1 easeIn animation. If you want smooth animation with a proper FLIP EFFECT without a white LINE (tested in iOS) -  Rollback to 0.4.0 fixes the issue.

**Comment by alongruss** [comment]
@sallypeters how so? can you show what you mean in "Completely changes the flip animation to a squash/expand animation" ?

**Comment by sallypeters** [comment]
@alongruss Here is the issue caused by this change , @fedeoo rolled the change back ... https://github.com/fedeoo/flip_card/issues/18

**Comment by sharpsan** [comment]
I am still getting this vertical line artifact in 0.6.0, but not consistently across all devices.  
Using Flutter 2.8.1.

**Comment by cmdbbang** [comment]
I resolved this issue by setting filterQuality to FilterQuality.none

```flutter
return Transform(
  transform: transform,
  filterQuality: FilterQuality.none,
  alignment: Alignment.center,
  child: child,
);
```
