### ISSUE TITLE
Default front side

### ISSUE THREAD

**Issue by PjoterKacprzak** [BrunoJurkovic/flip_card#36]
Hello,

I am having problems with List of Flip Cards, when i press FlipCard to flip it and then render next Flipcard from list, then its starts from the back side, is there any solution for that ?
E.g. to create FlipCard with default front side.

Thanks !

**Comment by BrunoJurkovic** [comment]
@PjoterKacprzak Thanks for opening an issue.

Your problem is that you are not using Keys. Provide a `UniqueKey` to each of your flip cards and your problem should be solved.
