### ISSUE TITLE
Is it possible to flip a card from another widget?

### ISSUE THREAD

**Issue by jamontes79** [BrunoJurkovic/flip_card#37]
At the beggining thanks for the component. :)

Is it possible to flip the card from other widget? For example from other FlipCard?

I would need to options but they are exclusives, for example gender, and I would like when you select one and it's flipped, then if the other option was selected come back to the front.

Thanks in advance

**Comment by BrunoJurkovic** [comment]
Hey there @jamontes79, thanks for opening an issue.

In the latest update to this package, you can now provide a controller to your flip_card item, and then you can call it from any place in your widget tree!

**Comment by RicentCB** [comment]
Hi @BrunoJurkovic I think, you should try to incorporate the controller documentation on the readme file. It was kind of hard to try to figure out, how it works.
Just a little recommendation.
Btw the package is really amazing, thanks for that

**Comment by samuel-rodrigues-silva** [comment]
controller is not working at all

**Comment by akhilksugathan** [comment]
How to use the controller? I want to flip the card with a button, Button changes the content in the cards but I want to reverse the card to the front if it is on the back side.

**Comment by ciriousjoker** [comment]
(I updated the [README](https://github.com/fedeoo/flip_card/blob/master/README.md) to include documentation about this)
