### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by britannio** [BrunoJurkovic/flip_card#38]
https://dart.dev/null-safety/migration-guide

**Comment by leynier** [comment]
Any update about this guys? I could help with this.

**Comment by lucagonzalez** [comment]
Is this project abandoned?

**Comment by princestha** [comment]
does anyone have a fork with null safety migration until i can find a replacement?

**Comment by mellowcello77** [comment]
Also need null safety here. Is there a workaround? Literally the only package left I cant migrate.

**Comment by BrunoJurkovic** [comment]
I am making a null safety fork and will contact this person to see if I could maintain the package.

**Comment by BrunoJurkovic** [comment]
Here, add this to your `package.yaml.`

```yaml
  flip_card:
    git:
      url: https://github.com/BrunoJurkovic/flip_card.git
```

NOTE: This also implements the proposed changes from @CiriousJoker, so here is the usage 
for the flip card controller: 
```dart
FlipCardController _controller = FlipCardController();
 
 _controller.hint(
   // optional
   duration: Duration(milliseconds: 400),
   // optional
   total: Duration(milliseconds: 900),
 );
 
 FlipCard(
   direction: FlipDirection.HORIZONTAL,
   controller: _controller,
   onFlip: () {
     //
   },
   back: Center(
     child: Container(
       child: ProjectFrontWidget(
         project: widget.project,
       ),
     ),
   ),
   front: Container(
     color: Colors.red,
     child: Center(
       child: ProjectBackWidget(
         project: widget.project,
       ),
     ),
   ),
 );
```

The duration will only run if not flipped yet and not already animating.
Animation runs for the duration and reverses afterward. The total duration will be used for this animation only and resets afterward.

Enjoy, tell me if there are any issues, from my testing everything works.

**Comment by ciriousjoker** [comment]
@BrunoJurkovic Thanks for your effort. Unfortunately, I doubt this project will be maintained again at any point.
I suggest you make a fork and the fork becomes the "official" package that people can install via direct url if they stumble across these issues.

**Comment by BrunoJurkovic** [comment]
I might make a fork and publish it under a similar name on pub.dev

**Comment by feibyte** [comment]
THanks @BrunoJurkovic  Resolved in https://github.com/fedeoo/flip_card/pull/39

**Comment by mellowcello77** [comment]
@BrunoJurkovic Thanks for the work done on this, appreciate it.
