### ISSUE TITLE
On the web, clicking turns the entire window and causes an error

### ISSUE THREAD

**Issue by kevin4dhd** [BrunoJurkovic/flip_card#41]
I don't know if my code is wrong, or it is a library error, please clarify this for me, but I have a list where when I click, it seems that the whole screen turns around and causes an error

![image](https://user-images.githubusercontent.com/22886367/115432413-f07ba480-a1cb-11eb-9577-6d39a95a5ef1.png)
![image](https://user-images.githubusercontent.com/22886367/115432507-0ee1a000-a1cc-11eb-8151-9871e6e345c6.png)

Another exception was thrown: RuntimeError: memory access out of bounds

Code:
![image](https://user-images.githubusercontent.com/22886367/115432561-21f47000-a1cc-11eb-9427-56adce37442b.png)

Code CardArmaBack:

import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:valorant_brasil/data/model/arma_model.dart';
import 'package:valorant_brasil/theme/colors_theme.dart';
import 'package:valorant_brasil/theme/text_theme.dart';

class CardArmaBack extends StatelessWidget {
  final Armas arma;
  CardArmaBack(this.arma);
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 250,
      child: Stack(children: [
        Container(
          child: Transform(
            alignment: Alignment.center,
            transform: Matrix4.rotationY(math.pi),
            child: Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                    image: NetworkImage(
                        'https://raw.githubusercontent.com/kauemurakami/valorant-br-api/master/images/armas/${arma.nome.toLowerCase()}.png'),
                    fit: BoxFit.cover),
              ),
            ),
          ),
        ),
        Container(
          margin: EdgeInsets.only(left: 24.0),
          width: Get.width,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                padding: EdgeInsets.only(top: 8.0, right: 8.0),
                width: Get.width,
                child: Text(
                  arma.descricao,
                  style: bannerArmaBack,
                ),
              ),
              Container(
                margin: EdgeInsets.only(top: 8.0),
                height: 30,
                width: Get.width,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Container(
                        width: 80,
                        decoration: BoxDecoration(
                            border: Border.all(width: 1, color: mainColor)),
                        child: Center(
                            child: Text(
                          'Distância',
                          style: TextStyle(color: mainColor),
                        ))),
                    Expanded(
                      child: ListView.builder(
                          scrollDirection: Axis.horizontal,
                          itemCount: arma.distncia.length,
                          itemBuilder: (context, index) {
                            return Container(
                                height: 70,
                                width: 80,
                                decoration: BoxDecoration(
                                    border:
                                        Border.all(width: 1, color: mainColor)),
                                child: Center(
                                  child: Text(
                                    arma.distncia[index],
                                    style: TextStyle(color: mainColor),
                                  ),
                                ));
                          }),
                    ),
                  ],
                ),
              ),
              Container(
                  height: 30,
                  width: Get.width,
                  child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Container(
                            width: 80,
                            decoration: BoxDecoration(
                                border: Border.all(width: 1, color: mainColor)),
                            child: Center(
                                child: Text(
                              'Cabeça',
                              style: TextStyle(color: mainColor),
                            ))),
                        Expanded(
                          child: ListView.builder(
                              scrollDirection: Axis.horizontal,
                              itemCount: arma.dano.length,
                              itemBuilder: (context, index) {
                                return Container(
                                    height: 70,
                                    width: 80,
                                    decoration: BoxDecoration(
                                        border: Border.all(
                                            width: 1, color: mainColor)),
                                    child: Center(
                                        child: Text(arma.dano[index].cabeca,
                                            style:
                                                TextStyle(color: mainColor))));
                              }),
                        ),
                      ])),
              Container(
                  height: 30,
                  width: Get.width,
                  child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Container(
                            width: 80,
                            decoration: BoxDecoration(
                                border: Border.all(width: 1, color: mainColor)),
                            child: Center(
                                child: Text(
                              'Corpo',
                              style: TextStyle(color: mainColor),
                            ))),
                        Expanded(
                          child: ListView.builder(
                              scrollDirection: Axis.horizontal,
                              itemCount: arma.dano.length,
                              itemBuilder: (context, index) {
                                return Container(
                                    height: 70,
                                    width: 80,
                                    decoration: BoxDecoration(
                                        border: Border.all(
                                            width: 1, color: mainColor)),
                                    child: Center(
                                        child: Text(
                                      arma.dano[index].corpo,
                                      style: TextStyle(color: mainColor),
                                    )));
                              }),
                        ),
                      ])),
              Container(
                  height: 30,
                  width: Get.width,
                  child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Container(
                            width: 80,
                            decoration: BoxDecoration(
                                border: Border.all(width: 1, color: mainColor)),
                            child: Center(
                                child: Text(
                              'Pernas',
                              style: TextStyle(color: mainColor),
                            ))),
                        Expanded(
                          child: ListView.builder(
                              scrollDirection: Axis.horizontal,
                              itemCount: arma.dano.length,
                              itemBuilder: (context, index) {
                                return Container(
                                    height: 70,
                                    width: 80,
                                    decoration: BoxDecoration(
                                        border: Border.all(
                                            width: 1, color: mainColor)),
                                    child: Center(
                                        child: Text(
                                      arma.dano[index].pernas,
                                      style: TextStyle(color: mainColor),
                                    )));
                              }),
                        )
                      ])),
            ],
          ),
        ),
      ]),
    );
  }
}

**Comment by treniere** [comment]
Your code is not wrong, I have the same problem. Works like a charm on mobile but broken on web. Waiting for a little fix

**Comment by monteiroricardo** [comment]
Any news? I have the same problem

**Comment by ciriousjoker** [comment]
Same issue here, although my card contains a MarkdownWidget (flutter_markdown). Flipping an empty container works fine.

For me, the issue happens when the MarkdownWidget contains too many paragraphs, so it seems like it is some sort of memory overflow when flipping big objects.

---

As a quickfix, turning off the new canvaskit renderer and enabling the html renderer correctly renders the card at the cost of significant performance hits.

**Comment by ciriousjoker** [comment]
Upgrading from Flutter 2.0.6 to Flutter 2.2.0 seemed to fix the issue.

@kevin4dhd Can you confirm this?

**Comment by bytelyus** [comment]
Hi there... was facing same issue. I was on 2.0.3 and upgrading to lastest (2.2.3) semms to fix the issue. Confirmed over here

**Comment by BrunoJurkovic** [comment]
Thanks, will close this now.
