### ISSUE TITLE
Flip Once?

### ISSUE THREAD

**Issue by bobwiller** [BrunoJurkovic/flip_card#44]
How would you prevent the card from flipping to the front again?  Essentially I would like to be able to flip only once.
Thanks,
Bob

**Comment by ciriousjoker** [comment]
You can turn off automatic toggling and toggle manually (and only do so if its currently on front)

**Comment by yunchiri** [comment]
how can i  turn on , turn off toggling?

**Comment by yunchiri** [comment]
oh I see
thanks!

set
flipcard.flipOnTouch : false
and using controller event
