### ISSUE TITLE
Display bug after flip when GoogleMaps on card

### ISSUE THREAD

**Issue by jjbois31** [BrunoJurkovic/flip_card#45]
Hello,

I have a Flipcard with a GoogleMaps map inside, and when flipping it, there is a display bug as we can still see a very thin stretched image of the map at the bottom of the screen (see screenshots and video). It only appears on iOS, not on Android. 
Any idea on how to fix it ?

Thanks.

![Simulator Screen Shot - iPhone 12 - 2021-08-01 at 00 42 14](https://user-images.githubusercontent.com/53739520/127754101-52026323-6679-4392-948c-98fc5484090b.png)
![Simulator Screen Shot - iPhone 12 - 2021-08-01 at 00 42 18](https://user-images.githubusercontent.com/53739520/127754102-064aab9c-e69f-422a-893f-a07a20a41030.png)

https://user-images.githubusercontent.com/53739520/127754100-7c49180c-d9cb-4e70-916e-73549c13c0a1.mp4

**Comment by BrunoJurkovic** [comment]
I cannot replicate this, is this still persistent? A quick fix that came to mind is checking what the front side is and unloading the Google Maps widget. This would be more efficient for memory and would probably fix it.

Let me know!
