### ISSUE TITLE
How to use controller?

### ISSUE THREAD

**Issue by akhilksugathan** [BrunoJurkovic/flip_card#47]
I am building a quiz application and have next button to change the question and answer on both sides of the card. But the problem is, if the card is on answer side(backside), clicking the next button shows answer for the next question. I want to automatically reverse the card to the question side with the next button click, if it is on the answer side.

**Comment by ciriousjoker** [comment]
(I updated the [README](https://github.com/fedeoo/flip_card/blob/master/README.md) to include documentation about this)
