### ISSUE TITLE
Can I change the animation time of the card dynamically?

### ISSUE THREAD

**Issue by kpk-i710** [BrunoJurkovic/flip_card#48]
I can set the animation time myself like ? cardKey.currentState! .ToggleCard (duration: Duration (seconds: 1); can't find how to set parameters

**Comment by ciriousjoker** [comment]
togglecard will always use the speed of the whole widget, so you have to pass the value during widget creation.

**Comment by adamsyy** [comment]
hey i am interested in solving this issue, can anyone guide me, please?

**Comment by kpk-i710** [comment]
> hey i am interested in solving this issue, can anyone guide me, please?

I was able to make such an animation and change its time dynamically only from this video https://www.youtube.com/watch?v=Jd7HtBZR6fg

**Comment by adamsyy** [comment]
thanks buddy, will try to do

**Comment by adamsyy** [comment]
by the way, is the issue solved?

**Comment by adamsyy** [comment]
:(

**Comment by kpk-i710** [comment]
> :(
found a solution, but not quite perfect, there it turns out that the final speed variable is set for the switching speed, so I rewrote all the code from the package into my project and changed the final speed to the usual speed now.

**Comment by kpk-i710** [comment]
> :(

found a solution, but not quite perfect, there it turns out that the final speed variable is set for the switching speed, so I rewrote all the code from the package into my project and changed the final speed to the usual speed now.

**Comment by BrunoJurkovic** [comment]
Please open another issue if this is still persistent, closing this as of now
