### ISSUE TITLE
How can I have continue more than 2 flips with different UI at each flip?

### ISSUE THREAD

**Issue by Hiteshc29** [BrunoJurkovic/flip_card#53]

**Comment by BrunoJurkovic** [comment]
Could you provide more details, what do you mean by 2 flips, do you have an example?

**Comment by HannesGitH** [comment]
i think the request is to flip from A to B and then to C and so on, aka changing the invisible side to another widget while its invisable

**Comment by BrunoJurkovic** [comment]
Closing this as there is no further elaboration.
