### ISSUE TITLE
[BUG] White blurry line in the middle of the card. Looks like it does not load properly. 

### ISSUE THREAD

**Issue by Edvardunsvag** [BrunoJurkovic/flip_card#59]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by ciriousjoker** [comment]
@Edvardunsvag
The template is meant to be filled in. At least fill out the steps to reproduce or explain where there's a blurry line.

**Comment by BrunoJurkovic** [comment]
Closing this for now as the PR is invalid.
