### ISSUE TITLE
[BUG] isFront is incorrectly updated for skew & hint

### ISSUE THREAD

**Issue by ciriousjoker** [BrunoJurkovic/flip_card#60]
## Expected Behavior

`isFront` should only be updated when the animation completes AND the card is fully flipped.

## Current Behavior

`isFront` is updated after every animation, including animations that don't fully flip a card, like `controller.skew()`.

## Possible Solution

Instead of subscribing to the animation controller status changes, we could wait for the animation to finish when calling `toggleCard` and only update `isFront` in that function.

## Steps to Reproduce

1. Call controller.skew()
2. Observe that `isFront` is now incorrect.

## Context (Environment)

I want to use skew to indicate on hover that the card is flippable. I do this by calling `skew(0.1)` followed by `skew(0)` on mouse exit. The second `skew(0)` now incorrectly flips the card because it thinks its flipped.

The same thing probably happens for `hint()`

**Comment by BrunoJurkovic** [comment]
@ciriousjoker Is this fixed via the PR or not?

**Comment by ciriousjoker** [comment]
@BrunoJurkovic my bad, accidentally committed to the wrong upstream, meant to create a PR instead.

**Comment by BrunoJurkovic** [comment]
Hmm, is my action needed in any way? I am currently on the GitHub mobile app so I don't really see much detail regarding the PR

**Comment by ciriousjoker** [comment]
@BrunoJurkovic You already merged it, everything's fine. I force pushed to an earlier state which should be fine given that this is a small repo and it was only in an incorrect state for like a minute.

Can you please publish this to pub.dev? Note that I haven't increased the version number. I suggest 0.6.1
