### ISSUE TITLE
Can't respond to click events

### ISSUE THREAD

**Issue by lizhuoyuan** [BrunoJurkovic/flip_card#62]
```
ScaleTransition(
                  scale: _animation,
                  child: FlipCard(
                    controller: flipCardController,
                    key: cardKey,
                    front: buildFrontWidget(),
                    back: buildBackWidget(),
                  ),
                )
```
Currently only happens in 0.6.0, 0.5.0 has no problem
If you replace FlipCard with GestureDetector, you can respond to click events
Maybe there is a conflict with ScaleTransition

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/lizhuoyuan/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by Russiarain** [comment]
I have the same issue,but it seems there's nothing to do with the transition.

When flip card can't respond to touch event, I noticed that FlipCard
State is null for those widgets.

**Comment by BrunoJurkovic** [comment]
Hey there, @lizhuoyuan, thanks for opening an issue.

So, the issue seems to be that sometimes the widget doesn't flip? Could you please clarify the issue and write a expected behaviour vs actual behaviour and I will be glad to look at your issue!
