### ISSUE TITLE
[BUG] Web page gets frozen after a few animations

### ISSUE THREAD

**Issue by renanboni** [BrunoJurkovic/flip_card#63]
I have a row with 4 cards that are wrapped in a MouseRegion and I'm using the onEnter and onExit methods to handle the animation.

` Widget _buildFlipAnimation() {
    return MouseRegion(
      onEnter: (event) => {cardKey.currentState?.toggleCard()},
      onExit: (event) => {cardKey.currentState?.toggleCard()},
      child: FlipCard(
          key: cardKey,
          front: _buildFront(),
          back: _buildRear(),
          flipOnTouch: false),
    );
  }`

After hovering a few times the page gets frozen, I need to close it down and open it again.

## Expected Behavior
The animation should not break the page.

## Current Behavior
The animation breaks/lags the page.

## Steps to Reproduce
https://www.youtube.com/watch?v=_vmL0zpTgwQ

**Comment by BrunoJurkovic** [comment]
Improperly written, please fill out all of the sections and make a new PR.
