### ISSUE TITLE
[BUG] onFlipDone is a bit slow

### ISSUE THREAD

**Issue by MLZ91** [BrunoJurkovic/flip_card#65]
There is a delay between the time when the flip animation is done (visually) and the time when onlipDone is called. I would say its about half a second. 

It would be nice if this delay could be shortened.

Right now I am using a workaround with Future.delayed with 350 ms after calling toggleCard().

**Comment by BrunoJurkovic** [comment]
Hey, thanks for reporting,

is this an issue you still face?

**Comment by MLZ91** [comment]
Sorry I didnt have time to check it before. 

Works great now, thanks!
