### ISSUE TITLE
[BUG] The method 'toggleCardWithoutAnimation' isn't defined for the type 'FlipCardState

### ISSUE THREAD

**Issue by 1gogarci** [BrunoJurkovic/flip_card#87]
## Expected Behavior

Usage of toggleCardWithoutAnimation method should be available for a FlipCardState object.

## Current Behavior

Error on compilation from FlutterFlow: "The method 'toggleCardWithoutAnimation' isn't defined for the type 'FlipCardState'. Try correcting the name to the name of an existing method, or defining a method named 'toggleCardWithoutAnimation'."

## Steps to Reproduce

1. Create a widget in Flutterflow
2. Add a custom StatefulWidget and include a flipcard on it
3. Create a function in the class and call the "toggleCardWithoutAnimation" method from the flipcard object.
4. Compile and check result

## Context (Environment)

I´m working on a custom app using FlutterFlow.

I´m currently working on a custom widget to deliver a feature in one of the pages of the app.

In the widget I´m using a customized StatefulWidget class object that include a flipcard inside.

I use 3 of those objects to show 3 customized flipcards that are arranged on top of each other to show different content on the page. 

There are some specific cases when I need one of those cards to re-arrange its position in the stack and flip itself but I do not want the flipping effect to be shown as it "breaks" the experience I want to deliver.

I was expecting that the method 'toggleCardWithoutAnimation' would work that out but It is not available. The rest of methods seem to work fine.

I have the package imported
import 'package:flip_card/flip_card.dart';

I´m working on a Flutterflow App 

## Detailed Description

Review status of the "toggleCardWithoutAnimation" method in the class/package and make it available to be used.

**Comment by 1gogarci** [comment]
UPDATE: 
My mistake. 

I added the 0.7.0. version dependency at flutter flow and now I do not get the error at compiling. Nevertheless, i do get an error on runtime when trying to create a flipcard and using the "side" parameter.

I also get an exception output from "nosuchmethod" method when trying to use the "toggleCardWithoutAnimation" method on the flipcardstate object. 

I will update this post with additional information, code and screenshots.

**Comment by ciriousjoker** [comment]
Please read the documentation (or the changelog in this case):
> Added function toggleCardWithoutAnimation to the controller that toggles the card instantly

You need to create a controller and use that to modify the state of the flip card. Why did you think calling toggleCardWithoutAnimation on the state would work? Did FlutterFlow suggest it? Keep in mind I haven't worked with FlutterFlow yet.

**Comment by ciriousjoker** [comment]
- I just realized that the function was removed by this pr: https://github.com/BrunoJurkovic/flip_card/pull/81

Keep that in mind when updating the package version to the next version once its released (it should still work for the time being though!)

**Comment by 1gogarci** [comment]
Hi Cirious and thank you for the reply.

I tried to read as much as possible and did some research in the docs before posting.

The issue here, apart from me learning flutter and flutterflow on the go (apologies if I'm a bit lost), is that I am not sure which flipcard version I've been working with.

I've been following this documentation: 
[https://pub.dev/documentation/flip_card/latest/flip_card/FlipCardState/toggleCardWithoutAnimation.html](https://pub.dev/documentation/flip_card/latest/flip_card/FlipCardState/toggleCardWithoutAnimation.html)

As ToggleCard() has been working so far from the State I was assuming the other method should work too.

Yesterday, I added the dependencies for 0.7.0 at FlutterFlow, wouldn't that method be available? 
![Captura de pantalla 2023-11-21 a las 17 49 04](https://github.com/BrunoJurkovic/flip_card/assets/97983190/04a37a5f-3685-4ebc-9b2a-9a42378b1b79)

Or is that PR you mentioned the one referenced in the dependency? (edit: you already answered this)

Also, when I use the side parameter (which is commented in the screenshot):
![Captura de pantalla 2023-11-21 a las 17 49 41](https://github.com/BrunoJurkovic/flip_card/assets/97983190/1d41638d-e2e3-4448-aab9-362787397056)

this is the error I get in runtime:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
dart_sdk.js:29145 The following JSNoSuchMethodError was thrown building
dart_sdk.js:29145 StackItem-[LabeledGlobalKey<_StackItemState>#15fd6](dirty, state: _StackItemState#88e4a):
dart_sdk.js:29145 TypeError: Cannot read properties of undefined (reading 'FRONT')
dart_sdk.js:29145 
dart_sdk.js:29145 The relevant error-causing widget was:
dart_sdk.js:29145   StackItem-[LabeledGlobalKey<_StackItemState>#15fd6]

``` 

It does work for other enums like _FlipDirection_ or _Fill_ but crashes for _CardSide_.

**Comment by ciriousjoker** [comment]
- The PR I linked isn't yet relevant, since those changes are only on Github but not pub.dev so far.
- You're not really supposed to call methods on the state itself. I guess we only still have those because of backwards compatibility. Instead, create a controller and call methods on the controller.
- The runtime error might be a completely separate issue

I don't really have time to maintain this and the original maintainer doesn't seem to have time and/or care unfortunately.

**Comment by 1gogarci** [comment]
Hi Cirious, thanks.

I will try to refactor and use the controller instead. 

Would that change also prevent from the need to call "setState" and provoque a "rebuilding"?

My custom code is near to work out the features I'm looking for my app but i think it needs a rework to optimize those aspects. Are there any recommended lectures, documentation, course regarding setState and rebuilds? 

As for the CardSide runtime error, would it be better to publish a different ticket?

Thanks
Gorka

**Comment by ciriousjoker** [comment]
- runtime error is separate. Check existing errors and if no one else had the same issue, create a new one
- I highly recommend using Flutter without FlutterFlow first, since it hides a lot of the underlying functionality, which makes debugging much harder and it also probably slows down learning 
- controller should trigger rebuilds automatically, if it doesn't that's a new issue

**Comment by 1gogarci** [comment]
Hi again.

I'm looking to set up the project on Flutter to allow for better debugging as you say but that is not possible at the moment. 

I'll follow your suggestions nevertheless and move it as soon as possible.

I will keep the thread open for some days just in case.

Thanks again!
