### ISSUE TITLE
AndroidX?

### ISSUE THREAD

**Issue by kbrmimbyl** [BrunoJurkovic/flip_card#9]
Hi, thanks for a great plugin! I'm using flip_card in a project which we're migrating to AndroidX. Is this plugin already migrated? I couldn't find any info in the changelog on pub...

**Comment by simolus3** [comment]
I'm using this plugin on an Android app with AndroidX and didn't run into any problems. Plugins like these typically don't need migrations because they don't have any native code, so that's probably why it's not mentioned in the changelog.

**Comment by kbrmimbyl** [comment]
I guess for me the whole AndroidX thing is such a scare that I didn't want to take any chances... we're in production... Thanks for clarifying, @simolus3 !
